.PHONY: clean All

All:
	@echo "----------Building project:[ c_project - Debug ]----------"
	@cd "c_project" && "$(MAKE)" -f  "c_project.mk"
clean:
	@echo "----------Cleaning project:[ c_project - Debug ]----------"
	@cd "c_project" && "$(MAKE)" -f  "c_project.mk" clean
